FROM alpine:3.7

ARG APP_HOME=/app
RUN mkdir "$APP_HOME"
COPY . $APP_HOME
WORKDIR $APP_HOME

RUN apk add --no-cache build-base ruby ruby-dev ruby-json ruby-bundler \
    && bundle install \
    && apk del build-base ruby-dev \
    && rm -rf /root/.bundle/cache/ \

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
