global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#anton-kostin'
