version: '3.3'
services:

  post_db:
    image: "mongo:${MONGO_VERSION}"
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db

  ui:
    #build: ./ui
    image: "${USER_NAME}/ui:${UI_VERSION}"
    ports:
      - "${UI_OUTER_PORT}:9292/tcp"
    networks:
      - front_net

  post:
    #build: ./post-py
    image: "${USER_NAME}/post:${POST_VERSION}"
    networks:
      - front_net
      - back_net

  comment:
    #build: ./comment
    image: "${USER_NAME}/comment:${COMMENT_VERSION}"
    networks:
      - front_net
      - back_net

  prometheus:
    image: ${USER_NAME}/prometheus:v2.1.0
    ports:
      - '9090:9090'
    networks:
      - front_net
      - back_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net

volumes:
  post_db:

networks:
  front_net:
  back_net:
