---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: reddit
    component: ui
spec:
  type: NodePort
  #LoadBalancer
  ports:
  - port: 9292 #80
    nodePort: 32093
    protocol: TCP
    targetPort: 9292
  selector:
    app: reddit
    component: ui
